version: '3.8'

services:
  shop_kz:
    image: shop_kz_docker
    build:
      context: shop_kz
      dockerfile: Dockerfile
    depends_on:
      - db
    logging:
      driver: journald
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

  bot:
    image: bot_docker
    build:
      context: bot
      dockerfile: Dockerfile
    depends_on:
      - db
    logging:
      driver: journald
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - shop_kz_pg_data:/var/lib/postgresql/data

volumes:
  shop_kz_pg_data: